#!/bin/sh

##################################################
# Dockerイメージを登録する
#
# Environment Variables
#  DOCKER_USER: DockerHubのユーザー名
#  DOCKER_PASS: DockerHubのパスワード
#
# Precondition
#  Need to set DOCKER_USER and DOCKER_PASS.
##################################################

# Set shell option
set -eu

# Load some environmental values
source ./gcc/hooks/env.sh

# Register in Docker Hub
source ./gcc/../lib/dockerhub.sh
pushImage ${DOCKER_USER} ${DOCKER_PASS} ${D_IMAGE} ${GCC} ${GCC_VERSION} ${GCC_LATEST}