version: 2
jobs:
  build-baseos:
    working_directory: ~/baseos
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./baseos/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up serverspec environment
          command: |
            apk add ruby ruby-rdoc ruby-etc
            gem install bundler
            bundle update --bundler
            bundle install --path vendor/bundler
      # - run:
      #     name: Testing Docker
      #     command: |
      #       source ./baseos/run_spec.sh
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./baseos/hooks/deploy

  build-apache:
    working_directory: ~/apache
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./apache/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up serverspec environment
          command: |
            apk add ruby ruby-rdoc ruby-etc
            gem install bundler
            bundle update --bundler
            bundle install --path vendor/bundler
      - run:
          name: Testing Docker
          command: |
            source ./apache/hooks/post_build
      # - run:
      #     name: Testing Docker
      #     command: |
      #       source ./apache/run_spec.sh
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./apache/hooks/deploy

  build-gcc:
    working_directory: ~/gcc
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./gcc/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up serverspec environment
          command: |
            apk add ruby ruby-rdoc ruby-etc
            gem install bundler
            bundle update --bundler
            bundle install --path vendor/bundler
      # - run:
      #     name: Testing Docker
      #     command: |
      #       source ./gcc/run_spec.sh
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./gcc/hooks/deploy

  build-nginx:
    working_directory: ~/nginx
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./nginx/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up serverspec environment
          command: |
            apk add ruby ruby-rdoc ruby-etc
            gem install bundler
            bundle update --bundler
            bundle install --path vendor/bundler
      # - run:
      #     name: Testing Docker
      #     command: |
      #       source ./nginx/run_spec.sh
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./nginx/hooks/deploy

  build-php:
    working_directory: ~/php
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./php/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up serverspec environment
          command: |
            apk add ruby ruby-rdoc ruby-etc
            gem install bundler
            bundle update --bundler
            bundle install --path vendor/bundler
      # - run:
      #     name: Testing Docker
      #     command: |
      #       source ./php/run_spec.sh
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./php/hooks/deploy

  build-redis:
    working_directory: ~/redis
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./redis/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up serverspec environment
          command: |
            apk add ruby ruby-rdoc ruby-etc
            gem install bundler
            bundle update --bundler
            bundle install --path vendor/bundler
      # - run:
      #     name: Testing Docker
      #     command: |
      #       source ./redis/run_spec.sh
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./redis/hooks/deploy

workflows:
  version: 2
  build-and-test-and-deploy:
    jobs:
      - build-baseos:
          context: dockerhub
          filters:
            branches:
              only: baseos/master
      - build-apache:
          context: dockerhub
          filters:
            branches:
              only: apache/master
      # - build-gcc:
      #     context: dockerhub
      #     filters:
      #       branches:
      #         only: gcc/master
      - build-nginx:
          context: dockerhub
          filters:
            branches:
              only: nginx/master
      - build-php:
          context: dockerhub
          filters:
            branches:
              only: php/master
      - build-redis:
          context: dockerhub
          filters:
            branches:
              only: redis/master

