version: 2.1

executors:
  default:
    docker:
      - image: docker:stable-git
    working_directory: ~/repo

jobs:
  build-baseos:
    executor: default
    working_directory: ~/baseos
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./baseos/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up serverspec environment
          command: |
            apk add ruby ruby-rdoc ruby-etc
            gem install bundler
            bundle update --bundler
            bundle install --path vendor/bundler
      # - run:
      #     name: Testing Docker
      #     command: |
      #       source ./baseos/run_spec.sh
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./baseos/hooks/deploy

  build-apache:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./repo/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up inspec environment
          command: |
            apk add build-base git libffi-dev libxml2-dev openssh-client ruby ruby-bigdecimal ruby-dev ruby-etc ruby-rdoc ruby-webrick
            gem install bundler
            bundle install --path vendor/bundler
      - run:
          name: Testing Docker
          command: |
            source ./repo/hooks/post_build
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./repo/hooks/deploy

  build-gcc:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./repo/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up inspec environment
          command: |
            apk add build-base git libffi-dev libxml2-dev openssh-client ruby ruby-bigdecimal ruby-dev ruby-etc ruby-rdoc ruby-webrick
            gem install bundler
            bundle install --path vendor/bundler
      - run:
          name: Testing Docker
          command: |
            source ./repo/hooks/post_build
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./repo/hooks/deploy

  build-nginx:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./repo/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up inspec environment
          command: |
            apk add build-base git libffi-dev libxml2-dev openssh-client ruby ruby-bigdecimal ruby-dev ruby-etc ruby-rdoc ruby-webrick
            gem install bundler
            bundle install --path vendor/bundler
      - run:
          name: Testing Docker
          command: |
            source ./repo/hooks/post_build
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./repo/hooks/deploy

  build-php:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./repo/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up inspec environment
          command: |
            apk add build-base git libffi-dev libxml2-dev openssh-client ruby ruby-bigdecimal ruby-dev ruby-etc ruby-rdoc ruby-webrick
            gem install bundler
            bundle install --path vendor/bundler
      - run:
          name: Testing Docker
          command: |
            source ./repo/hooks/post_build
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./repo/hooks/deploy

  build-redis:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./repo/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up inspec environment
          command: |
            apk add build-base git libffi-dev libxml2-dev openssh-client ruby ruby-bigdecimal ruby-dev ruby-etc ruby-rdoc ruby-webrick
            gem install bundler
            bundle install --path vendor/bundler
      - run:
          name: Testing Docker
          command: |
            source ./repo/hooks/post_build
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./repo/hooks/deploy

workflows:
  version: 2
  build-and-test-and-deploy:
    jobs:
      - build-baseos:
          context: dockerhub
          filters:
            branches:
              only: baseos/master
      - build-apache:
          context: dockerhub
          filters:
            branches:
              only: apache/master
      # - build-gcc:
      #     context: dockerhub
      #     filters:
      #       branches:
      #         only: gcc/master
      - build-nginx:
          context: dockerhub
          filters:
            branches:
              only: nginx/master
      - build-php:
          context: dockerhub
          filters:
            branches:
              only: php/master
      - build-redis:
          context: dockerhub
          filters:
            branches:
              only: redis/master

