version: 2.1

executors:
  default:
    docker:
      - image: docker:stable-git
    working_directory: ~/repo

jobs:
  build-baseos:
    executor: default
    working_directory: ~/baseos
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./baseos/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./baseos/hooks/deploy

  build-apache:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.11
      - run:
          name: Building Docker
          command: |
            source ./apache/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up inspec environment
          command: |
            apk add build-base git libffi-dev libxml2-dev openssh-client ruby ruby-bigdecimal ruby-dev ruby-etc ruby-rdoc ruby-webrick
            gem install bundler
            bundle config set --local path 'vendor/bundler'
            bundle install
      - run:
          name: Testing Docker
          command: |
            source ./apache/hooks/post_build
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./apache/hooks/deploy

  build-gcc:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./gcc/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up inspec environment
          command: |
            apk add build-base git libffi-dev libxml2-dev openssh-client ruby ruby-bigdecimal ruby-dev ruby-etc ruby-rdoc ruby-webrick
            gem install bundler
            bundle install --path vendor/bundler
      - run:
          name: Testing Docker
          command: |
            source ./gcc/hooks/post_build
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./gcc/hooks/deploy

  build-nginx:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./nginx/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up inspec environment
          command: |
            apk add build-base git libffi-dev libxml2-dev openssh-client ruby ruby-bigdecimal ruby-dev ruby-etc ruby-rdoc ruby-webrick
            gem install bundler
            bundle install --path vendor/bundler
      - run:
          name: Testing Docker
          command: |
            source ./nginx/hooks/post_build
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./nginx/hooks/deploy

  build-php:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./php/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up inspec environment
          command: |
            apk add build-base git libffi-dev libxml2-dev openssh-client ruby ruby-bigdecimal ruby-dev ruby-etc ruby-rdoc ruby-webrick
            gem install bundler
            bundle install --path vendor/bundler
      - run:
          name: Testing Docker
          command: |
            source ./php/hooks/post_build
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./php/hooks/deploy

  build-redis:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            source ./redis/hooks/build
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up inspec environment
          command: |
            apk add build-base git libffi-dev libxml2-dev openssh-client ruby ruby-bigdecimal ruby-dev ruby-etc ruby-rdoc ruby-webrick
            gem install bundler
            bundle install --path vendor/bundler
      - run:
          name: Testing Docker
          command: |
            source ./redis/hooks/post_build
      - deploy:
          name: Deploy to Docker Hub
          command: |
            source ./redis/hooks/deploy

workflows:
  version: 2
  build-and-test-and-deploy:
    jobs:
      - build-baseos:
          context: dockerhub
          filters:
            branches:
              only: baseos/master
      - build-apache:
          context: dockerhub
          filters:
            branches:
              only: apache/master
      # - build-gcc:
      #     context: dockerhub
      #     filters:
      #       branches:
      #         only: gcc/master
      - build-nginx:
          context: dockerhub
          filters:
            branches:
              only: nginx/master
      - build-php:
          context: dockerhub
          filters:
            branches:
              only: php/master
      - build-redis:
          context: dockerhub
          filters:
            branches:
              only: redis/master

