version: 2
jobs:
  build-baseos:
    working_directory: ~/baseos
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            docker image build . -t ${DOCKER_USER}/base_os:centos_7 -f baseos/Dockerfile.centos
            docker image build . -t ${DOCKER_USER}/base_os:ubuntu_bionic -f baseos/Dockerfile.ubuntu
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up serverspec environment
          command: |
            apk add ruby ruby-rdoc ruby-etc
            gem install bundler
            bundle update --bundler
            bundle install --path vendor/bundler
      - run:
          name: Testing Docker
          command: |
            source run_spec.sh
      - deploy:
          name: Deploy to Docker Hub
          command: |
            echo $DOCKER_PASS | base64 -d | \
            docker login -u ${DOCKER_USER} --password-stdin
            docker image push ${DOCKER_USER}/base_os:centos_7
            docker image push ${DOCKER_USER}/base_os:ubuntu_bionic
            docker logout

  build-apache:
    working_directory: ~/apache
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            DOCKER_BUILDKIT=1 docker image build . -t ${DOCKER_USER}/apache:latest -f apache/Dockerfile
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up serverspec environment
          command: |
            apk add ruby ruby-rdoc ruby-etc
            gem install bundler
            bundle update --bundler
            bundle install --path vendor/bundler
      - run:
          name: Testing Docker
          command: |
            source run_spec.sh
      - deploy:
          name: Deploy to Docker Hub
          command: |
            echo $DOCKER_PASS | base64 -d | \
            docker login -u ${DOCKER_USER} --password-stdin
            docker image push ${DOCKER_USER}/apache:latest
            docker logout

  build-php:
    working_directory: ~/php
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.09.3
      - run:
          name: Building Docker
          command: |
            DOCKER_BUILDKIT=1 docker image build . -t ${DOCKER_USER}/php:latest -f php/Dockerfile
      - run:
          name: Update system
          command: |
            apk update
            apk upgrade
      - run:
          name: Set up serverspec environment
          command: |
            apk add ruby ruby-rdoc ruby-etc
            gem install bundler
            bundle update --bundler
            bundle install --path vendor/bundler
      - run:
          name: Testing Docker
          command: |
            source run_spec.sh
      - deploy:
          name: Deploy to Docker Hub
          command: |
            echo $DOCKER_PASS | base64 -d | \
            docker login -u ${DOCKER_USER} --password-stdin
            docker image push ${DOCKER_USER}/php:latest
            docker logout
workflows:
  version: 2
  build-and-test-and-deploy:
    jobs:
      - build-baseos:
          context: dockerhub
          filters:
            branches:
              only: baseos/master
      - build-apache:
          context: dockerhub
          filters:
            branches:
              only: apache/master
      - build-php:
          context: dockerhub
          filters:
            branches:
              only: php/master
