#!/bin/sh

##################################################
# Dockerイメージを作成する
##################################################

# Load some environmental values
. ./nginx/hooks/env.sh

# Building a docker image
echo "Building a docker image"
docker image build . \
--build-arg PCRE=${PCRE} \
--build-arg PCRE_PAKAGE=${PCRE_PAKAGE} \
--build-arg PCRE_PAKAGE_FILE=${PCRE_PAKAGE_FILE} \
--build-arg PCRE_URL=${PCRE_URL} \
--build-arg NGINX=${NGINX} \
--build-arg NGINX_PAKAGE=${NGINX_PAKAGE} \
--build-arg NGINX_PAKAGE_FILE=${NGINX_PAKAGE_FILE} \
--build-arg NGINX_URL=${NGINX_URL} \
-t ${D_IMAGE} \
-f ./nginx/Dockerfile
