#!/bin/sh

##################################################
# Dockerイメージを登録する
#
# Environment Variables
#  DOCKER_USER: DockerHubのユーザー名
#  DOCKER_PASS: DockerHubのパスワード
#
# Precondition
#  Need to set DOCKER_USER and DOCKER_PASS.
##################################################

# Set shell option
set -eu

# Load some environmental values
. ./php/hooks/env.sh

# Register in Docker Hub
. ./php/../lib/dockerhub.sh
pushImage ${DOCKER_USER} ${DOCKER_PASS} ${D_IMAGE} ${PHP} ${PHP_VERSION} ${PHP_LATEST}